auto &vmap = views::transform;
auto &viota = views::iota;
auto &vtake = views::take;
auto &vdrop = views::drop;
auto &vjoin = views::join;
auto &vkeys = views::keys;
auto &vvalues = views::values;
auto &rsize = ranges::size;
using ranges::iterator_t;
using ranges::range;
using ranges::range_difference_t;
using ranges::range_reference_t;
using ranges::range_value_t;
using ranges::ref_view;
using ranges::sentinel_t;
